"""On-ramp commands: scaffold and inspect an agent package from a decorated class.

``surgeval init-agent`` is the bridge between the trial path (``@se.agent`` plus
``surgeval run``) and the publication path (a versioned, digest-pinned package
directory). It writes what the decorator inferred — nothing is guessed at write
time, and the weights pin is always the real SHA-256 of the file on disk.
"""

from __future__ import annotations

import argparse
import contextlib
import importlib
import os
import shutil
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any

from or_audit.errors import ScoreContractError, TaskContractError
from or_audit.eval.integrity import file_sha256
from or_audit.eval.loader import load_agent
from surgeval.decorators import (
    AgentBinding,
    binding_for,
    capability_toml,
    describe_agent,
)

_PLACEHOLDER_WEIGHTS = """{
  "surgeval_placeholder": true,
  "note": "Replace this file with your real weights, then re-run",
  "command": "surgeval init-agent <module:Class> --out <dir> --weights <file> --force"
}
"""

_RUNNER_TEMPLATE = '''"""Generated by `surgeval init-agent`. This is your package now: edit freely.

The harness runs this file in an isolated plugin-host process and calls the
factory named in agent.toml. ``{module}`` must be importable from this
directory when the package runs.
"""

from __future__ import annotations

import importlib
import inspect
import os
import sys
from pathlib import Path
from typing import Any

for _entry in (str(Path(__file__).resolve().parent), os.getcwd()):
    if _entry not in sys.path:
        sys.path.insert(0, _entry)

MODULE = "{module}"
CLASS = "{cls_name}"


def _build(weights_path: Any) -> Any:
    target = getattr(importlib.import_module(MODULE), CLASS)
    if "weights_path" in inspect.signature(target).parameters:
        return target(weights_path=weights_path)
    return target()

{factories}'''

_PREDICTOR_FACTORY = '''
def load_predictor(*, root: Any = None, weights_path: Any = None) -> Any:
    """Return the object the harness calls ``predict(item)`` on."""
    del root
    return _build(weights_path)
'''

_POLICY_FACTORY = '''
def load_policy(*, root: Any = None, weights_path: Any = None) -> Any:
    """Return the object the harness calls ``reset()``/``act(obs, step=...)`` on."""
    del root
    return _build(weights_path)
'''


@contextlib.contextmanager
def _cwd_on_path() -> Iterator[None]:
    entry = os.getcwd()
    added = entry not in sys.path
    if added:
        sys.path.insert(0, entry)
    try:
        yield
    finally:
        if added and entry in sys.path:
            sys.path.remove(entry)


def _import_target(spec: str) -> type[Any]:
    """Import ``module:Class`` with the current working directory on ``sys.path``.

    This imports — and therefore *executes* — the named module in this process.
    That is deliberate: ``init-agent``/``describe-agent`` are local developer
    commands pointed at the developer's own source tree, the same trust level as
    running ``python -c "import mymodel"``. They are not an upload path. Anything
    untrusted must go through the isolated plugin-host runtime instead.
    """
    module_name, separator, class_name = spec.partition(":")
    if not separator or not module_name or not class_name:
        raise TaskContractError(f"target must be module:Class, got {spec!r}")
    with _cwd_on_path():
        try:
            module = importlib.import_module(module_name)
        except ImportError as exc:
            raise TaskContractError(
                f"cannot import module {module_name!r} from {os.getcwd()}: {exc}"
            ) from exc
    target = getattr(module, class_name, None)
    if target is None:
        raise TaskContractError(f"module {module_name!r} has no attribute {class_name!r}")
    if not isinstance(target, type):
        raise TaskContractError(f"{spec} is not a class, it is a {type(target).__name__}")
    return target


def _vendor_module(target: type[Any], out: Path) -> str | None:
    """Copy a single-file top-level model module into the package, or explain why not.

    A published package has to be importable wherever it runs. A one-file module
    is copied in so the package is self-contained; a module inside an installed
    package is left alone, because copying one file out of a package would ship a
    broken import.
    """
    module_name = target.__module__
    if "." in module_name or module_name in {"__main__", "builtins"}:
        return None
    module = sys.modules.get(module_name)
    source = getattr(module, "__file__", None)
    if source is None:
        return None
    source_path = Path(source).resolve()
    if source_path.suffix != ".py" or (source_path.parent / "__init__.py").exists():
        return None
    destination = out / f"{module_name}.py"
    if destination.resolve() == source_path:
        return None
    shutil.copyfile(source_path, destination)
    return destination.name


def _write_package(
    binding: AgentBinding,
    out: Path,
    *,
    module_name: str,
    weights_source: Path | None,
) -> tuple[Path, str]:
    """Write agent.toml, runner.py, and the weights file; return (weights, real pin)."""
    out.mkdir(parents=True, exist_ok=True)

    weights_name = weights_source.name if weights_source is not None else "weights.json"
    weights_file = out / weights_name
    if weights_source is not None:
        if weights_source.resolve() != weights_file.resolve():
            shutil.copyfile(weights_source, weights_file)
    else:
        weights_file.write_text(_PLACEHOLDER_WEIGHTS, encoding="utf-8")
    # The pin is computed from the bytes that were actually written: an agent
    # package whose declared digest is not its content is a broken package.
    weights_pin = file_sha256(weights_file)

    factories = ""
    if "predict" in binding.methods:
        factories += _PREDICTOR_FACTORY
    if "act" in binding.methods:
        factories += _POLICY_FACTORY
    (out / "runner.py").write_text(
        _RUNNER_TEMPLATE.format(
            module=module_name,
            cls_name=binding.cls_name,
            factories=factories,
        ),
        encoding="utf-8",
    )

    entrypoint = binding.entrypoint_symbol
    agent_toml = "\n".join(
        [
            'format_version = "2"',
            f'id = "{binding.agent_id}"',
            f'agent_version = "{binding.version}"',
            f'kind = "{binding.kind}"',
            f'weights_pin = "{weights_pin}"',
            f'weights_path = "{weights_name}"',
            "",
            capability_toml(binding.capability),
            "[runtime]",
            'kind = "local"',
            'protocol_version = "1"',
            f'entrypoint = "runner.py:{entrypoint}"',
            "timeout_sec = 600.0",
            "",
        ]
    )
    (out / "agent.toml").write_text(agent_toml, encoding="utf-8")
    return weights_file, weights_pin


def _init_agent(args: argparse.Namespace) -> int:
    try:
        target = _import_target(args.target)
        binding = binding_for(target)
        out = Path(args.out).resolve()
        if out.exists() and any(out.iterdir()) and not args.force:
            raise TaskContractError(f"{out} is not empty; pass --force to overwrite it")
        weights_source = Path(args.weights).resolve() if args.weights else None
        if weights_source is not None and not weights_source.is_file():
            raise TaskContractError(f"weights file {weights_source} does not exist")
        module_name = target.__module__
        weights_file, weights_pin = _write_package(
            binding, out, module_name=module_name, weights_source=weights_source
        )
        vendored = _vendor_module(target, out)
        package = load_agent(out)
    except (TaskContractError, ScoreContractError) as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 1
    print(f"wrote agent package: {out}")
    print(f"  id           {package.id}@{package.agent_version}")
    print(f"  kind         {package.kind}")
    print(f"  entrypoint   {package.runtime.entrypoint if package.runtime else ''}")
    print(f"  weights      {weights_file.name}  sha256:{weights_pin}")
    if weights_source is None:
        print("               placeholder content; re-run with --weights <file> for real weights")
    if vendored is not None:
        print(f"  vendored     {vendored} (the package is self-contained)")
    else:
        print(f"  imports      {module_name} must be importable where this package runs")
    if binding.schema_wildcard:
        print("  binding      WILDCARD: no schemas declared, so this binds any task on")
        print(f"               interface {binding.interface!r} without a shape check")
    else:
        print("  binding      verified against declared schemas")
    print(f"next: surgeval run -t <task> -a {args.out} --out runs/first")
    return 0


def _describe_agent(args: argparse.Namespace) -> int:
    try:
        target = _import_target(args.target)
        summary = describe_agent(target)
    except (TaskContractError, ScoreContractError) as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        return 1
    print(summary)
    return 0


def register(sub: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    """Attach the on-ramp subcommands to a CLI subparser action."""
    init = sub.add_parser(
        "init-agent",
        help="scaffold a publishable agent package from a @surgeval.agent class",
    )
    init.add_argument("target", help="module:Class of a decorated agent")
    init.add_argument("--out", required=True, help="package directory to write")
    init.add_argument("--weights", help="weights file to copy in and pin (default: placeholder)")
    init.add_argument("--force", action="store_true", help="overwrite a non-empty output directory")
    init.set_defaults(func=_init_agent)

    describe = sub.add_parser(
        "describe-agent",
        help="print the capability a @surgeval.agent class declares",
    )
    describe.add_argument("target", help="module:Class of a decorated agent")
    describe.set_defaults(func=_describe_agent)


__all__ = ["register"]
